// ── Accent colour themes ───────────────────────────────────────────────────────
// All Tailwind class strings must appear as full literals here so JIT includes them.

export const THEMES = {
  violet: {
    id: 'violet',
    name: 'Violet',
    bg: 'bg-violet-500',
    bgHover: 'hover:bg-violet-400',
    bgSubtle: 'bg-violet-500/20',
    text: 'text-violet-400',
    border: 'border-violet-500/40',
    ring: 'ring-violet-500/50',
    hex: '#8B5CF6',
  },
  blue: {
    id: 'blue',
    name: 'Ocean',
    bg: 'bg-blue-500',
    bgHover: 'hover:bg-blue-400',
    bgSubtle: 'bg-blue-500/20',
    text: 'text-blue-400',
    border: 'border-blue-500/40',
    ring: 'ring-blue-500/50',
    hex: '#3B82F6',
  },
  emerald: {
    id: 'emerald',
    name: 'Emerald',
    bg: 'bg-emerald-500',
    bgHover: 'hover:bg-emerald-400',
    bgSubtle: 'bg-emerald-500/20',
    text: 'text-emerald-400',
    border: 'border-emerald-500/40',
    ring: 'ring-emerald-500/50',
    hex: '#10B981',
  },
  orange: {
    id: 'orange',
    name: 'Fire',
    bg: 'bg-orange-500',
    bgHover: 'hover:bg-orange-400',
    bgSubtle: 'bg-orange-500/20',
    text: 'text-orange-400',
    border: 'border-orange-500/40',
    ring: 'ring-orange-500/50',
    hex: '#F97316',
  },
  rose: {
    id: 'rose',
    name: 'Rose',
    bg: 'bg-rose-500',
    bgHover: 'hover:bg-rose-400',
    bgSubtle: 'bg-rose-500/20',
    text: 'text-rose-400',
    border: 'border-rose-500/40',
    ring: 'ring-rose-500/50',
    hex: '#F43F5E',
  },
  cyan: {
    id: 'cyan',
    name: 'Cyan',
    bg: 'bg-cyan-500',
    bgHover: 'hover:bg-cyan-400',
    bgSubtle: 'bg-cyan-500/20',
    text: 'text-cyan-400',
    border: 'border-cyan-500/40',
    ring: 'ring-cyan-500/50',
    hex: '#06B6D4',
  },
  red: {
    id: 'red',
    name: 'True Red',
    bg: 'bg-red-600',
    bgHover: 'hover:bg-red-500',
    bgSubtle: 'bg-red-600/20',
    text: 'text-red-500',
    border: 'border-red-600/40',
    ring: 'ring-red-600/50',
    hex: '#DC2626',
  },
  pink: {
    id: 'pink',
    name: 'Electric Pink',
    bg: 'bg-[#FF1493]',
    bgHover: 'hover:bg-[#e0117f]',
    bgSubtle: 'bg-[#FF1493]/20',
    text: 'text-[#FF1493]',
    border: 'border-[#FF1493]/40',
    ring: 'ring-[#FF1493]/50',
    hex: '#FF1493',
  },
  white: {
    id: 'white',
    name: 'White',
    bg: 'bg-[#E8E8E8]',
    bgHover: 'hover:bg-[#d0d0d0]',
    bgSubtle: 'bg-[#E8E8E8]/20',
    text: 'text-[#E8E8E8]',
    border: 'border-[#E8E8E8]/40',
    ring: 'ring-[#E8E8E8]/50',
    hex: '#E8E8E8',
  },
  black: {
    id: 'black',
    name: 'Black',
    bg: 'bg-[#2D2D2D]',
    bgHover: 'hover:bg-[#3d3d3d]',
    bgSubtle: 'bg-[#2D2D2D]/20',
    text: 'text-[#2D2D2D]',
    border: 'border-[#2D2D2D]/40',
    ring: 'ring-[#2D2D2D]/50',
    hex: '#2D2D2D',
  },
}

export function getTheme(id) {
  return THEMES[id] || THEMES.violet
}
